from typing import Any, Dict, Literal, NewType, Tuple

# ------------------------------ Inference ------------------------------

# Identifier for an inference API
InferenceApiIdentifier = NewType("InferenceApiIdentifier", str)

# Identifies a model on an inference API
ModelId = NewType("ModelId", str)

# URL to an OpenAI-compatible inference API
InferenceApiUrl = NewType("InferenceApiUrl", str)

# API key for an inference API
ApiKey = NewType("ApiKey", str)

# Identifier for a preset
PresetIdentifier = Literal["openrouter", "openai"]

# Prompt Template identifier
PromptTemplateIdentifier = Literal["default"]

# Prompt Template
PromptTemplate = NewType("PromptTemplate", str)

# Prompt
Prompt = NewType("Prompt", str)

Response = NewType("Response", str)

Role = Literal["system", "user", "assistant"]

PromptVar = Literal[
    "python_version",
    "exception_type_name",
    "exception_message",
    "exception_attributes",
    "immediate",
    "traceback",
    "call_stack_section",
    "cause_section",
    "context_section",
]

# ------------------------------ Exception ------------------------------

PythonVersion = NewType("PythonVersion", str)
ExceptionTypeName = NewType("ExceptionTypeName", str)
ExceptionMessage = NewType("ExceptionMessage", str)
ExceptionAttributes = NewType("ExceptionAttributes", Dict[str, Any])

# Full traceback string
Traceback = NewType("Traceback", str)

# Cause of the exception
Cause = NewType("Cause", str)

# Context of the exception
Context = NewType("Context", str)

# Function name
FnName = NewType("FnName", str)

# Source code path
SourceCodePath = NewType("SourceCodePath", str)

# Source code
SourceCode = NewType("SourceCode", str)

# Source code snippet
SourceCodeSnippet = NewType("SourceCodeSnippet", str)

# Line number offset (1-based)
LineNumberOffset = NewType("LineNumberOffset", int)

# Secret
Secret = NewType("Secret", str)

# Redacted secret
RedactedSecret = NewType("RedactedSecret", str)


# ------------------------------ Framework ------------------------------

FrameworkName = NewType("FrameworkName", str)

Documentation = NewType("Documentation", str)

# NOTE: This code is generated by Claude Opus 4.5
# Array shape tuple (e.g., (3, 4, 5) for a 3D array)
ArrayShape = NewType("ArrayShape", Tuple[int, ...])

# Array dtype string (e.g., "float32", "int64")
ArrayDtype = NewType("ArrayDtype", str)

# Device name (e.g., "cpu", "cuda:0", "tpu:0")
DeviceName = NewType("DeviceName", str)

# Generic transformation type - JAX has vmap/jit, PyTorch has vmap/compile, etc.
TransformationType = Literal["vectorize", "parallelize", "compile", "differentiate"]
